### ISSUE TITLE
Replace deprecated self.call() with newer self.create_interface_score()

### ISSUE THREAD

**Issue by mr-rooftop** [icon-project/multisig-wallet#27]
in the ` _external_call` function `self.call()` is used to call an external SCORE:
https://github.com/icon-project/multisig-wallet/blob/72201bd59bffd374930542d95fbb129a3ca9a85b/multisig_wallet/multisig_wallet.py#L233

This function is deprecated and should be updated with its successor `self.create_interface_score()`

**Comment by sink772** [comment]
As you mentioned, `self.call()` is marked as deprecated method, and it has been recommended to use the alternative, `self.create_interface_score()`. This recommendation would be the best practice in typical scenarios.

In multisig-wallet case, however, it would not be workable, because we do not know the actual target method beforehand and we need to call a method dynamically in runtime.

Thus, we are going to remove the deprecation mark of `self.call` in the upcoming icon-service 1.7.0 release.

**Comment by mr-rooftop** [comment]
Alright, I understand, thank you very much!
